//These guys dance

public class VillageDancer extends FestiveVillager {

	private static final long serialVersionUID = 1L;

	public VillageDancer(Solid target, String message, double x, double y, boolean role) {
		super(target, message, x, y, 0);
		this.role = role;
		behavior = DANCE_UNTIL_DETECT_THEN_FLEE;
		intention = DANCE;
		/**
		 * All dancers have a (tx,ty) point. This is their dancing "reference point."
		 * They will try to move to that point, plus the vector generated by the dance.
		 **/
		this.tx = x;
		this.ty = y;
	}

}